# mashpad/melodies.py — children's-song melodies + a sequential note sequencer.
#
# Pure — no pygame, no numpy, no I/O (joins the purity test). main.py pulls the
# next note name off a MelodySequencer on every allowed spawn; audio.py plays the
# matching sounds/notes/<name>.wav. Note names here are the WAV filenames.
#
# Songs are authored in a compact letter notation so each transcription reads
# like sheet music and can be checked by eye against docs/piano-melodies-plan.md:
#   * a letter A–G is a natural note in the base octave (C major, no accidentals)
#   * a trailing "'" raises it one octave, a trailing "," drops it one octave
#   * "|" and whitespace are bar/rhythm separators and are ignored
# _parse() turns that into the ("g4", "c5", …) filenames the audio layer wants.

from __future__ import annotations

from dataclasses import dataclass

# The diatonic C-major note set generated by gen_notes.py (G4–C6). Kept as a
# literal here so this module stays pure/importable without numpy; a drift test
# (tests/test_melodies.py) asserts it matches gen_notes.NOTE_NAMES exactly.
NOTE_RANGE: tuple[str, ...] = (
    "g4", "a4", "b4", "c5", "d5", "e5", "f5", "g5", "a5", "b5", "c6",
)
_VALID = frozenset(NOTE_RANGE)

# Octave an unmarked letter lands in; "," drops one, "'" raises one. The audition
# winner was the C5-root xylophone, so unmarked C is c5 (design table +12).
_BASE_OCTAVE = 5


def _parse(notation: str) -> tuple[str, ...]:
    """Compact letter notation → note filenames.

    'C' → 'c5',  "C'" → 'c6',  'G,' → 'g4'. Bars ('|') and whitespace separate
    notes and are ignored. Raises ValueError on an unrecognised token so a
    fat-fingered transcription fails loudly at import instead of playing silence.
    """
    notes: list[str] = []
    for token in notation.replace("|", " ").split():
        letter = token[0].lower()
        suffix = token[1:]
        if letter not in "abcdefg":
            raise ValueError(f"bad note letter in token {token!r}")
        octave = _BASE_OCTAVE
        if suffix == "'":
            octave += 1
        elif suffix == ",":
            octave -= 1
        elif suffix != "":
            raise ValueError(f"bad octave mark in token {token!r}")
        notes.append(f"{letter}{octave}")
    return tuple(notes)


@dataclass(frozen=True)
class Song:
    """A named melody as an ordered tuple of note filenames (no durations)."""
    name: str
    notes: tuple[str, ...]


def _song(name: str, notation: str) -> Song:
    return Song(name, _parse(notation))


# Adding a melody = adding one _song(...) line here. Transcriptions are from
# memory (see docs/piano-melodies-plan.md) and verified by ear during MP-1.
SONGS: list[Song] = [
    _song(
        "London Bridge Is Falling Down",
        "G A G F E F G | D E F | E F G | G A G F E F G | D G E C",
    ),
    _song(
        "Twinkle Twinkle Little Star",
        "C C G G A A G | F F E E D D C | G G F F E E D | G G F F E E D | "
        "C C G G A A G | F F E E D D C",
    ),
    _song(
        "Mary Had a Little Lamb",
        "E D C D E E E | D D D | E G G | E D C D E E E E | D D E D C",
    ),
    _song(
        "Row Row Row Your Boat",
        "C C C D E | E D E F G | C' C' C' G G G E E E C C C | G F E D C",
    ),
    _song(
        "Hot Cross Buns",
        "E D C | E D C | C C C C D D D D | E D C",
    ),
    _song(
        "Frère Jacques",
        "C D E C | C D E C | E F G | E F G | G A G F E C | G A G F E C | "
        "C G, C | C G, C",
    ),
    _song(
        "Old MacDonald Had a Farm",
        "C C C G, A, A, G, | E E D D C | C C C G, A, A, G, | E E D D C",
    ),
]


def _validate(songs: list[Song]) -> None:
    """Every song must be non-empty and use only generated (in-range) notes."""
    for song in songs:
        if not song.notes:
            raise ValueError(f"song {song.name!r} has no notes")
        bad = [n for n in song.notes if n not in _VALID]
        if bad:
            raise ValueError(f"song {song.name!r} uses out-of-range notes {bad}")


_validate(SONGS)


class MelodySequencer:
    """Walks the song list one note per next() call, looping forever.

    Sequential: each next() returns the current song's next note; at a song's end
    it advances to the following song (the last song wraps back to the first). No
    RNG — the order is deterministic. A dropped note upstream (all mixer channels
    busy) is the caller's problem; the sequence still advances by one per call,
    which is the intended "any key = next note" behaviour.
    """

    def __init__(self, songs: list[Song] | None = None) -> None:
        self._songs = songs if songs is not None else SONGS
        if not self._songs:
            raise ValueError("MelodySequencer needs at least one song")
        self._song_idx = 0
        self._note_idx = 0

    def next(self) -> str:
        """Return the next note filename and advance the sequence."""
        song = self._songs[self._song_idx]
        note = song.notes[self._note_idx]
        self._note_idx += 1
        if self._note_idx >= len(song.notes):
            self._note_idx = 0
            self._song_idx = (self._song_idx + 1) % len(self._songs)
        return note

    @property
    def current_song(self) -> str:
        """Name of the song the next() call will draw its note from."""
        return self._songs[self._song_idx].name
