# Tests for Audio.play_for's effect-layer fallback (piano note vs. random ding):
#   - piano mode, note clip loaded        → the note plays, no ding
#   - piano mode, note clip NOT loaded    → falls back to a random ding
#   - dings mode (note=None)              → a random ding plays
#   - play_note returns True/False by whether a clip was found
#
# The fallback matters because sound_mode defaults to "piano" but the note WAVs
# are gitignored (generated by gen_notes at install time); without this fallback
# an install where gen_notes did not run would have a silent effect layer.
#
# Runs each scenario in a subprocess (like test_voice_fallback.py) so
# mashpad.audio / pygame are never imported into the pytest process and cannot
# break the purity assertion in test_keymap.py.

import subprocess
import sys


def _run(code: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)


# Shared preamble: build an Audio with stubbed playback so no mixer is needed.
_PRE = r"""
import sys
from mashpad.audio import Audio
from mashpad import config

class FakeSound:
    def __init__(self, tag):
        self.tag = tag
        self.vol = None
    def set_volume(self, v):
        self.vol = v

class FakeRng:
    def choice(self, seq):
        return seq[0]

class Spec:
    spoken_name = "cat"

def make(notes, effects):
    a = Audio.__new__(Audio)
    a._ok = True
    a._voice = {}
    a._notes = notes
    a._effects = effects
    a._master = 1.0
    a._played = []
    a._play = lambda s: a._played.append(s)
    return a
"""


def test_piano_note_loaded_plays_note_not_ding():
    proc = _run(_PRE + r"""
note = FakeSound("note")
ding = FakeSound("ding")
a = make({"g5": note}, [ding])
a.play_for(Spec(), FakeRng(), voice=None, note="g5")
if [s.tag for s in a._played] != ["note"]:
    print(f"FAIL: expected [note], got {[s.tag for s in a._played]}"); sys.exit(1)
if note.vol != config.EFFECT_VOLUME * 1.0:
    print(f"FAIL: note volume {note.vol}"); sys.exit(1)
sys.exit(0)
""")
    assert proc.returncode == 0, f"{proc.stdout}\n{proc.stderr}"


def test_piano_note_missing_falls_back_to_ding():
    proc = _run(_PRE + r"""
ding = FakeSound("ding")
a = make({}, [ding])                     # empty notes (gen_notes never ran)
a.play_for(Spec(), FakeRng(), voice=None, note="g5")
if [s.tag for s in a._played] != ["ding"]:
    print(f"FAIL: expected ding fallback, got {[s.tag for s in a._played]}"); sys.exit(1)
sys.exit(0)
""")
    assert proc.returncode == 0, f"{proc.stdout}\n{proc.stderr}"


def test_dings_mode_plays_ding():
    proc = _run(_PRE + r"""
note = FakeSound("note")
ding = FakeSound("ding")
a = make({"g5": note}, [ding])
a.play_for(Spec(), FakeRng(), voice=None, note=None)   # dings mode
if [s.tag for s in a._played] != ["ding"]:
    print(f"FAIL: expected ding, got {[s.tag for s in a._played]}"); sys.exit(1)
sys.exit(0)
""")
    assert proc.returncode == 0, f"{proc.stdout}\n{proc.stderr}"


def test_missing_note_and_no_effects_is_silent_no_crash():
    proc = _run(_PRE + r"""
a = make({}, [])                         # no notes AND no effects loaded
a.play_for(Spec(), FakeRng(), voice=None, note="g5")   # must not raise
if a._played:
    print(f"FAIL: expected silence, got {[s.tag for s in a._played]}"); sys.exit(1)
sys.exit(0)
""")
    assert proc.returncode == 0, f"{proc.stdout}\n{proc.stderr}"


def test_play_note_return_value():
    proc = _run(_PRE + r"""
note = FakeSound("note")
a = make({"g5": note}, [])
if a.play_note("g5") is not True:
    print("FAIL: loaded note should return True"); sys.exit(1)
if a.play_note("zz") is not False:
    print("FAIL: unknown note should return False"); sys.exit(1)
a._notes = {}
if a.play_note("g5") is not False:
    print("FAIL: empty notes should return False"); sys.exit(1)
sys.exit(0)
""")
    assert proc.returncode == 0, f"{proc.stdout}\n{proc.stderr}"
